apiVersion: v1
kind: Service
metadata:
  name: inference-rail
  labels:
    app: inference-rail
spec:
  selector:
    app: inference-rail
  ports:
    - name: http
      port: 80
      targetPort: 8000
